version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12 
    commands:
      - 'cd $HOME/.goenv && git pull --ff-only && cd -'
      - 'goenv install 1.17.5'
      - 'goenv local 1.17.5'
  pre_build:
    commands:
        - echo Start pre_build...
  build:
    commands:
      - echo Start build...
      - TAGS="bindata" make build
artifacts:
  files:
    - Procfile
    - gitea
    - custom/conf/app.ini
    - .ebextensions/1.config
